name: dahab
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  http: ^1.1.0
  oauth2: ^2.0.2
  provider: ^6.1.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
